name: Build Android APK

on:
  push:
    branches:
      - android-setup
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: إعطاء صلاحية التنفيذ لملف gradlew
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: FontMerger-APK
        path: app/build/outputs/apk/debug/app-debug.apk
